"""
Two tables:
  recordings - one row per uploaded file. Also acts as the job queue (status = 'queued').
  chunks     - one row per ~25s slice of a recording, so progress and retries are per-slice.
Audio bytes never go in the database; only the object-storage key does.
"""

import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class Recording(Base):
    __tablename__ = "recordings"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    # Random id generated by the browser. Scopes "my recordings" without a login system.
    owner_id: Mapped[str] = mapped_column(String(64), index=True)

    original_filename: Mapped[str] = mapped_column(String(255))
    content_type: Mapped[str] = mapped_column(String(100))
    size_bytes: Mapped[int] = mapped_column(BigInteger)
    storage_key: Mapped[str] = mapped_column(String(500))
    language_code: Mapped[str] = mapped_column(String(10))
    duration_seconds: Mapped[float | None] = mapped_column(Float)

    status: Mapped[str] = mapped_column(String(20), index=True)
    chunks_total: Mapped[int] = mapped_column(Integer, default=0)
    chunks_done: Mapped[int] = mapped_column(Integer, default=0)

    transcript: Mapped[str | None] = mapped_column(Text)
    summary: Mapped[str | None] = mapped_column(Text)
    error_message: Mapped[str | None] = mapped_column(Text)  # safe to show the user
    error_detail: Mapped[str | None] = mapped_column(Text)  # internal: HTTP bodies, tracebacks

    attempts: Mapped[int] = mapped_column(Integer, default=0)  # times a worker picked this job up
    locked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))  # worker heartbeat

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    uploaded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    chunks: Mapped[list["Chunk"]] = relationship(
        back_populates="recording", order_by="Chunk.idx", cascade="all, delete-orphan"
    )

    @property
    def can_retry(self) -> bool:
        # Retrying only makes sense if the file actually reached storage.
        return self.status == "failed" and self.uploaded_at is not None


class Chunk(Base):
    __tablename__ = "chunks"
    # The unique constraint is what makes chunk creation idempotent: a retried
    # job can never insert a second "chunk 3" for the same recording.
    __table_args__ = (UniqueConstraint("recording_id", "idx"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    recording_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("recordings.id", ondelete="CASCADE"), index=True)
    idx: Mapped[int] = mapped_column(Integer)
    start_seconds: Mapped[float] = mapped_column(Float)
    end_seconds: Mapped[float] = mapped_column(Float)

    status: Mapped[str] = mapped_column(String(20), default="pending")  # pending | done | failed
    transcript: Mapped[str | None] = mapped_column(Text)  # "" is valid: the slice had no speech
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    gnani_request_id: Mapped[str | None] = mapped_column(String(100))
    error_message: Mapped[str | None] = mapped_column(Text)

    recording: Mapped[Recording] = relationship(back_populates="chunks")
